"""Turns a pipeline run into clinician-facing decision support.

Rules this module follows, because clinicians will act on its output:
- Never claim a check passed if it did not run; list what was NOT checked.
- Never present model-reported likelihood as calibrated confidence.
- Label simulated reviewers as simulated.
- Every field is derived from the run; nothing is filled with plausible defaults.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from src.agents.base import is_parse_failure
from src.telemetry.metrics import PipelineRunResult

SEVERITY_RANK = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
DISCLAIMER = (
    "Decision support only. This output was generated by AI agents and has not been reviewed by a clinician. "
    "It must not replace clinical judgment, examination, or local protocols."
)


def _as_list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _clean(output: Any) -> Optional[Dict[str, Any]]:
    if output is None:
        return None
    if not isinstance(output, dict) or is_parse_failure(output):
        return {}
    return output


def _severity(value: Any) -> str:
    sev = str(value or "").upper().strip()
    return sev if sev in SEVERITY_RANK else "MEDIUM"


def _likelihood(value: Any) -> Optional[float]:
    if not isinstance(value, (int, float)):
        return None
    value = float(value)
    return round(value / 100.0 if value > 1 else value, 3)


def _describe(item: Any) -> str:
    if not isinstance(item, dict):
        return str(item)
    text = next((str(item[k]) for k in ("description", "issue", "detail", "finding", "claim") if item.get(k)), "")
    section = item.get("section") or item.get("field")
    return f"{text} ({str(section).replace('_', ' ')})" if text and section else text or ", ".join(f"{k}: {v}" for k, v in item.items())


def collect_alerts(raw: Dict[str, Any]) -> List[Dict[str, Any]]:
    alerts: List[Dict[str, Any]] = []
    safety = _clean(raw.get("safety"))
    for flag in _as_list((safety or {}).get("safety_flags")):
        if isinstance(flag, dict):
            alerts.append({
                "source": "Safety validator (AI)",
                "severity": _severity(flag.get("severity")),
                "category": str(flag.get("hazard_type") or "SAFETY").replace("_", " ").title(),
                "description": str(flag.get("description") or "").strip(),
                "action": str(flag.get("mitigation") or "").strip(),
            })
    verifier = _clean(raw.get("verifier"))
    for claim in _as_list((verifier or {}).get("flagged_claims")):
        if isinstance(claim, dict):
            alerts.append({
                "source": "Grounding verifier (AI)",
                "severity": _severity(claim.get("severity")),
                "category": "Unsupported claim",
                "description": f"\"{claim.get('claim', '')}\" - {claim.get('issue', '')}".strip(" -"),
                "action": "Confirm against the chart before relying on this statement.",
            })
    consistency = _clean(raw.get("consistency"))
    for item in _as_list((consistency or {}).get("inconsistencies_found")):
        alerts.append({
            "source": "Consistency checker (AI)",
            "severity": "HIGH" if (consistency or {}).get("consistency_status") == "SEVERE_CONTRADICTION" else "MEDIUM",
            "category": "Internal inconsistency",
            "description": _describe(item),
            "action": "Reconcile the findings with the proposed diagnosis.",
        })
    hitl = _clean(raw.get("hitl"))
    for amendment in _as_list((hitl or {}).get("required_amendments")):
        if amendment:
            alerts.append({
                "source": "Simulated attending review (AI, not a human)",
                "severity": "MEDIUM",
                "category": "Requested amendment",
                "description": str(amendment),
                "action": "Consider before finalizing the plan.",
            })
    return sorted(alerts, key=lambda a: SEVERITY_RANK[a["severity"]])


def _checks(raw: Dict[str, Any]) -> List[Dict[str, Any]]:
    verifier, safety = _clean(raw.get("verifier")), _clean(raw.get("safety"))
    consistency, hitl = _clean(raw.get("consistency")), _clean(raw.get("hitl"))

    def outcome(output: Optional[Dict[str, Any]], key: str) -> Optional[str]:
        if output is None:
            return None
        return str(output.get(key) or "UNREADABLE OUTPUT")

    return [
        {"name": "Grounding verifier", "covers": "claims not supported by the case text",
         "ran": verifier is not None, "outcome": outcome(verifier, "verification_status")},
        {"name": "Safety validator", "covers": "contraindications, missed red flags, unsafe delays",
         "ran": safety is not None, "outcome": outcome(safety, "safety_status")},
        {"name": "Consistency checker", "covers": "diagnosis vs. findings contradictions",
         "ran": consistency is not None, "outcome": outcome(consistency, "consistency_status")},
        {"name": "Simulated attending review", "covers": "attending-style review of the plan (simulated by AI, not a human)",
         "ran": hitl is not None, "outcome": outcome(hitl, "decision")},
    ]


def build_decision_support(result: PipelineRunResult, calibration: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    raw = result.raw_outputs or {}
    diagnosis = _clean(raw.get("diagnosis")) or {}
    research = _clean(raw.get("research")) or {}
    verifier = _clean(raw.get("verifier"))
    hitl = _clean(raw.get("hitl"))

    differentials = []
    for d in _as_list(diagnosis.get("differential_diagnoses")):
        if isinstance(d, dict) and (d.get("condition") or d.get("diagnosis")):
            differentials.append({
                "rank": d.get("rank"),
                "condition": str(d.get("condition") or d.get("diagnosis")),
                "model_likelihood": _likelihood(d.get("probability")),
                "justification": str(d.get("justification") or ""),
            })
    primary = str(diagnosis.get("primary_diagnosis") or "").strip()

    alerts = collect_alerts(raw)
    checks = _checks(raw)
    not_checked = [f"Not checked: {c['covers']} ({c['name']} did not run)." for c in checks if not c["ran"]]

    reasons: List[str] = []
    if not primary:
        reasons.append("The diagnosis agent did not return a readable diagnosis.")
    if result.parse_failures:
        reasons.append(f"Unreadable output from: {', '.join(result.parse_failures)}.")
    serious = [a for a in alerts if a["severity"] in ("CRITICAL", "HIGH")]
    if serious:
        reasons.append(f"{len(serious)} high-severity alert(s) raised.")
    if verifier and verifier.get("hallucination_detected"):
        reasons.append("The grounding verifier found claims not supported by the case text.")
    if hitl and str(hitl.get("decision", "")).upper() in ("REQUEST_REVISION", "REJECTED"):
        reasons.append(f"Simulated attending review returned {hitl.get('decision')}.")
    if result.revision_applied and result.initial_primary_diagnosis.lower() != primary.lower():
        reasons.append("The diagnosis changed after governance feedback. The checks below ran on the initial "
                       f"diagnosis ({result.initial_primary_diagnosis}); the revised diagnosis was not re-checked.")
    if result.revision_triggers and not result.revision_applied:
        reasons.append("Checks raised serious concerns but the revision step failed; review the concerns yourself.")
    attention = "HIGH" if reasons else "STANDARD"
    if not reasons:
        reasons.append("No issues were raised by the checks that ran. This is not a confirmation of correctness.")

    calibration_note = "Likelihoods are the model's own estimates; treat them as a ranking, not a probability."
    if calibration and (calibration.get("n") or 0) >= 20 and (calibration.get("ece") or 0) >= 0.1:
        calibration_note = (
            f"Likelihoods are the model's own estimates and were poorly calibrated on the benchmark "
            f"(expected calibration error {calibration['ece']}). Treat them as a ranking, not a probability."
        )

    next_steps = [str(s) for s in _as_list(diagnosis.get("recommended_next_steps") or diagnosis.get("recommended_tests")) if s]
    escalate_now = [f"{a['category']}: {a['description']}" for a in serious]
    positives = [str(p) for p in _as_list(research.get("pertinent_positives")) if p]
    negatives = [str(n) for n in _as_list(research.get("pertinent_negatives")) if n]

    handoff = {
        "situation": str(research.get("chief_complaint") or "").strip(),
        "background": "; ".join(
            str(x) for x in (research.get("demographics"), research.get("history_present_illness")) if x
        ),
        "assessment": (f"AI's leading consideration: {primary}" if primary else "No readable AI assessment")
        + (f"; also considered: {', '.join(d['condition'] for d in differentials[1:4])}" if len(differentials) > 1 else ""),
        "recommendation": "; ".join(s.rstrip(" .;") for s in next_steps[:4]) or "No next steps returned.",
        "escalate": escalate_now,
    }

    return {
        "attention": attention,
        "reasons": reasons,
        "diagnosis": {
            "primary": primary or None,
            "justification": str(diagnosis.get("primary_justification") or diagnosis.get("reasoning_steps") or ""),
            "differentials": differentials,
            "pertinent_positives": positives,
            "pertinent_negatives": negatives,
        },
        "alerts": alerts,
        "checks": checks,
        "not_checked": not_checked,
        "revision": {
            "closed_loop": result.closed_loop,
            "applied": result.revision_applied,
            "failed": bool(result.revision_triggers) and not result.revision_applied,
            "checks_ran_on": "initial diagnosis" if result.revision_applied else "final diagnosis",
            "initial_diagnosis": result.initial_primary_diagnosis or None,
            "final_diagnosis": primary or None,
            "triggers": result.revision_triggers,
            "rationale": str(diagnosis.get("revision_rationale") or ""),
        },
        "next_steps": next_steps,
        "escalate_now": escalate_now,
        "handoff": handoff,
        "calibration_note": calibration_note,
        "disclaimer": DISCLAIMER,
    }


def build_case_response(
    result: PipelineRunResult,
    governance_level: str,
    inference_mode: str,
    provider: str,
    model: str,
    calibration: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """API payload: decision_support plus the fields the legacy case-runner page reads."""
    support = build_decision_support(result, calibration)
    raw = result.raw_outputs or {}
    verifier, safety, hitl = _clean(raw.get("verifier")), _clean(raw.get("safety")), _clean(raw.get("hitl"))
    diag = support["diagnosis"]
    top = diag["differentials"][0]["model_likelihood"] if diag["differentials"] else None
    next_steps = support["next_steps"]

    return {
        "case_id": result.case_id,
        "governance_level": governance_level,
        "governance_name": result.variant_name,
        "inference_mode": inference_mode,
        "provider": provider,
        "model_used": model,
        "decision_support": support,
        "specialist_output": {
            "primary_diagnosis": diag["primary"],
            "confidence": top,
            "confidence_is_calibrated": False,
            "reasoning": diag["justification"],
            "differential_rankings": [
                {"diagnosis": d["condition"], "probability": d["model_likelihood"], "justification": d["justification"]}
                for d in diag["differentials"]
            ],
            "initial_plan": ", ".join(next_steps),
            "final_plan": ", ".join(next_steps),
            "soap_report": _clean(raw.get("report")) or {},
        },
        "research_grounding": {
            "guideline": None,
            "citation": None,
            "pertinent_positives": diag["pertinent_positives"],
            "pertinent_negatives": diag["pertinent_negatives"],
            "evidence_text": diag["justification"],
        },
        "verifier_findings": {
            "status": (verifier or {}).get("verification_status", "UNREADABLE") if verifier is not None else "NOT_RUN",
            "unsupported_claims": len(_as_list((verifier or {}).get("flagged_claims"))) if verifier is not None else None,
            "grounding_score": (verifier or {}).get("confidence_score") if verifier is not None else None,
        },
        "safety_interceptions": [
            {"type": a["category"], "severity": a["severity"], "agent": a["source"], "description": a["description"],
             "original_plan": ", ".join(next_steps), "revised_plan": a["action"]}
            for a in support["alerts"] if a["source"].startswith("Safety") and a["severity"] in ("CRITICAL", "HIGH")
        ],
        "safety_check_ran": safety is not None,
        "hitl_review": {
            "status": (hitl or {}).get("decision", "UNREADABLE") if hitl is not None else "NOT_RUN",
            "attending_notes": (hitl or {}).get("critique") if hitl is not None else None,
            "simulated": True,
            "gate_active": hitl is not None,
        },
        "telemetry": {
            "tokens_used": result.total_tokens,
            "latency_seconds": round(sum(s.latency_ms for s in result.agent_steps) / 1000.0, 2),
            "cost_usd": result.total_cost_usd,
            "model_name": model,
            "provider": provider,
            "live_inference": inference_mode == "LIVE_LLM",
        },
        "multi_agent_steps": [
            {"agent": s.agent_name, "role": s.role, "status": "COMPLETED", "latency_ms": round(s.latency_ms, 1),
             "tokens": s.total_tokens, "cost_usd": s.cost_usd, "preview": s.output_preview, "flags": s.flags}
            for s in result.agent_steps
        ],
    }
